---

- name: Making sure Chrony is installed
  package:
    name: chrony
    state: present
    
- name: Making changes to the Chrony config is uptodate
  template:
    src: "chrony.conf.j2"
    dest: "/etc/chrony/chrony.conf"
    owner: "root"
    group: "root"
    mode: "644"
  notify: restart chrony
  
- name: Ensure chrony services is started and enabled
  service:
    name: chrony
    state: started
    enabled: yes
